"""Add place field to listings

Revision ID: d5aadf6db390
Revises: 
Create Date: 2025-09-19 15:30:48.867064

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'd5aadf6db390'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("DELETE FROM listings")
    op.add_column('listings', sa.Column('place', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('listings', sa.Column('images', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'images')
    op.drop_column('listings', 'place')
    # ### end Alembic commands ###